---
- name: "<{{ item }}> Set custom facts"
  set_fact:
    allow_ssh: no
    firewall_file: firewall_http.j2
- name: "<{{ item }}> Setup container"
  include_role:
    name: container
    tasks_from: container

- name: "<{{ item }}> Install vlan in container"
  command: "pct exec {{ ctid }} /sbin/apk add vlan"

- name: "<{{ item }}> Create vlan interfaces"
  blockinfile:
    path: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/etc/network/interfaces"
    block: |
      {% for host in groups['containers'] %}
      {% if hostvars[host].vlan != '0' %}
      auto eth0.{{ hostvars[host].vlan }}
      iface eth0.{{ hostvars[host].vlan }} inet static
          address 10.0.{{ hostvars[host].vlan }}.{{ ctid }}
          netmask 255.255.255.0

      {% endif %}
      {% endfor %}
  register: bridge_task

# - name: "<{{ item }}> Restart container networking to enable vlans"
#   command: "pct exec {{ ctid }} /etc/init.d/networking restart"
#   when: bridge_task.changed

- name: Enable new interfaces
  command: "pct exec {{ ctid }} ifup eth0.{{ hostvars[ct].vlan }}"
  loop: "{{ groups['containers'] }}"
  loop_control:
    loop_var: ct
  when: bridge_task.changed and hostvars[ct].vlan != '0'

- name: "<{{ item }}> Create Letâ€™s Encrypt dir"
  file:
    path: "/{{ zfs_volume }}/subvol-{{ ctid }}-disk-0/home/user-data/ssl"
    state: directory
...

