---
- name: Set hostvars
  set_fact:
    host: "{{ hostvars[item] }}"
    main_domain: "{{ item }}"
    ctid: "{{ hostvars[item].ansible_ssh_extra_args }}"
    vlan: "{{ hostvars[item].vlan }}"

- name: Generate common secrets
  set_fact:
    passphrase: "{{ hostvars[item].passphrase | default(lookup('password', '/dev/null length=64')) }}"
    backup_passphrase: "{{ hostvars[item].backup_passphrase | default(lookup('password', '/dev/null length=64')) }}"
    backup_ssh_key: "{{ hostvars[item].backup_ssh_key | default(lookup('file', 'tmp/' + item + '-backup', errors='warn')) }}"
    backup_ssh_pub_key: "{{ hostvars[item].backup_ssh_pub_key | default(lookup('file', 'tmp/' + item + '-backup.pub', errors='warn')) }}"
    mail_account_passphrase: "{{ hostvars[item].mail_account_passphrase | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"

- name: Create other vars
  set_fact:
    zfs_volume: "rpool/data/encrypted-{{ ctid }}"
    vlan: "{% if vlan %}{{ vlan }}{% else %}{{ ctid }}{% endif %}"

- name: Call custom secrets generation
  include_role:
    name: "{{ hostvars[item].role }}"
    tasks_from: secrets

- name: Add Ansible Host
  add_host:
    name: "{{ item }}"
    domain: "{{ main_domain }}"
    ct_hostname: "{{ main_domain }}"
    ctid: "{{ ctid }}"
    zfs_volume_passphrase: "{{ passphrase }}"
    backup_passphrase: "{{ backup_passphrase }}"
    backup_ssh_key: "{{ backup_ssh_key }}"
    backup_ssh_pub_key: "{{ backup_ssh_pub_key }}"
    mail_account_passphrase: "{{ mail_account_passphrase }}"
    extra_secrets: "{{ extra_secrets }}"
    pool: "{{ zfs_volume }}"
    zfs_volumes:
      - "{{ zfs_volume }}/subvol-{{ ctid }}-disk-0"
    ip: "10.0.{{ vlan }}.{{ ctid }}"
    vlan: "{{ vlan }}"
...
