---
- name: Set hostvars
  set_fact:
    host: "{{ hostvars[item] }}"
    main_domain: "{{ item }}"
    ctid: "{{ hostvars[item].ansible_ssh_extra_args }}"
    vlan: "{{ hostvars[item].vlan }}"
- name: Create ZFS volume passphrase
  set_fact:
    passphrase: "{{ lookup('password', '/dev/null length=64') }}"
  when: passphrase is not defined
- name: Create other vars
  set_fact:
    zfs_volume: "rpool/data/encrypted-{{ ctid }}"
    vlan: "{% if vlan %}{{ vlan }}{% else %}{{ ctid }}{% endif %}"

- name: Create backup passphrase
  set_fact:
    backup_passphrase: "{{ lookup('password', '/dev/null length=64') }}"
    when: backup_passphrase is not defined

- name: Add Ansible Host
  add_host:
    name: "{{ item }}"
    domain: "{{ main_domain }}"
    ct_hostname: "{{ main_domain }}"
    ctid: "{{ ctid }}"
    zfs_volume_passphrase: "{{ passphrase }}"
    backup_passphrase: "{{ backup_passphrase }}"
    zfs_pool: "{{ zfs_volume }}"
    zfs_volumes:
      - "{{ zfs_volume }}/subvol-{{ ctid }}-disk-0"
    ip: "10.0.{{ vlan }}.{{ ctid }}"
    vlan: "{{ vlan }}"
...
