image: alpine-3.11-default_20200425_amd64.tar.xz
ostype: alpine
disk_size: 8
cpu_cores: 1
cpu_units: 1024
memory: 512
swap: 512
allow_ssh: no
firewall_file: firewall.j2
borgmatic_config_file: borgmatic.j2
