---
- name: Upgrade system
  apk:
    upgrade: yes
    update_cache: yes

- name: Install tzdata
  apk:
    name: tzdata

- name: Copy timezone data
  copy:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    remote_src: yes

- name: Install fail2ban
  apk:
    name: fail2ban

- name: Start fail2ban
  service:
    name: fail2ban
    state: started
    runlevel: default

- name: Install ssh-honeypot
  apk:
    name: ssh-honeypot
    repository: 
      - http://dl-cdn.alpinelinux.org/alpine/edge/testing
      - http://dl-cdn.alpinelinux.org/alpine/v3.10/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.10/community

- name: Create ssh-honeypot (because alpine one is broken)
  openssh_keypair:
    path: /usr/share/ssh-honeypot/honeypot.rsa
    type: rsa

- name: Make ssh-honeypot run on port 22
  copy:
    src: files/ssh-honeypot
    dest: /etc/conf.d/ssh-honeypot
    remote_src: no

- name: Start ssh-honeypot
  service:
    name: ssh-honeypot
    state: started
    runlevel: default

- name: Install node-exporter
  apk:
    name: prometheus-node-exporter
    repository:
      - http://dl-cdn.alpinelinux.org/alpine/edge/testing
      - http://dl-cdn.alpinelinux.org/alpine/v3.10/main
      - http://dl-cdn.alpinelinux.org/alpine/v3.10/community

- name: Create node_exporter run dir
  file:
    path: /var/run/prometheus
    state: directory
    owner: prometheus
    group: prometheus

# - name: Make Node Exporter listen on localhost only
#   template:
#     src: templates/default_node_exporter
#     dest: /etc/default/prometheus-node-exporter
#   register: prometheus_default_conf

- name: Start Node Exporter
  service:
    name: node-exporter
    state: started

# - name: Restart Node Exporter
#   service:
#     name: node-exporter
#     state: restarted
#   when: prometheus_default_conf.changed
...
