---
- name: Get existing OSP secret key
  set_fact:
    osp_secret_key: "{{ hostvars[item].osp_secret_key | default(lookup('password', '/dev/null length=64')) }}"
    osp_password_salt: "{{ hostvars[item].osp_password_salt | default(lookup('password', '/dev/null length=16')) }}"
    ejabberd_pass: "{{ hostvars[item].ejabberd_pass | default(lookup('password', '/dev/null length=64 chars=ascii_letters,digits')) }}"
- name: Set extra secrets
  set_fact:
    extra_secrets:
      osp_secret_key: "{{ osp_secret_key }}"
      osp_password_salt: "{{ osp_password_salt }}"
      ejabberd_pass: "{{ ejabberd_pass }}"

# - name: Get existing Wordpress password
#   set_fact:
#     wordpress_admin_password: "{{ hostvars[item].wordpress_admin_password }}"
#   when: hostvars[item].wordpress_admin_password is defined

# - name: Create mail account password
#   set_fact:
#     wordpress_admin_password: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
#   when: wordpress_admin_password is not defined

# - name: Get existing Wordpress DB password
#   set_fact:
#     database_password: "{{ hostvars[item].database_password }}"
#   when: hostvars[item].database_password is defined

# - name: Create Wordpress DB password
#   set_fact:
#     database_password: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
#   when: database_password is not defined

# - name: Get existing Wordpress DB admin password
#   set_fact:
#     database_admin_password: "{{ hostvars[item].database_admin_password }}"
#   when: hostvars[item].database_admin_password is defined

# - name: Create Wordpress DB admin password
#   set_fact:
#     database_admin_password: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
#   when: database_admin_password is not defined

# - name: Set extra secrets
#   set_fact:
#     extra_secrets:
#       wordpress_admin_password: "{{ wordpress_admin_password }}"
#       database_password: "{{ database_password }}"
#       database_admin_password: "{{ database_admin_password }}"
...
