---
- name: Set custom facts
  set_fact:
    image: alpine-3.10-default_20190626_amd64.tar.xz
    ostype: alpine
    disk_size: 8
    cpu_cores: 1
    cpu_units: 1024
    memory: 512
    swap: 512
    firewall_file: firewall.j2
    allow_ssh: yes
    redirected_ports: []
- name: Setup container
  include_role:
    name: container
    tasks_from: container
...
